// 友尽厨房菜品订单数据
function addOrderNo(list) {
    return list.map((item, idx) => ({ ...item, orderNo: idx + 1 }));
}
const mockData = {
    teamA: addOrderNo([
        { name: "A类汉堡", price: 40, ingredients: ["汉堡胚", "生菜", "番茄", "肉饼", "煎蛋", "芝士"] },
        { name: "A类沙拉", price: 35, ingredients: ["生菜", "黄瓜x2", "小番茄x2", "玉米粒"] },
        { name: "A类水果茶", price: 25, ingredients: ["西瓜", "百香果", "柠檬", "绿茶"] },
        { name: "汉堡", price: 40, ingredients: ["汉堡胚", "生菜", "肉饼", "煎蛋", "芝士x2"] },
        { name: "水果茶", price: 20, ingredients: ["百香果", "柠檬", "绿茶"] },
        { name: "沙拉", price: 30, ingredients: ["生菜", "黄瓜x2", "小番茄x2"] },
        { name: "沙拉", price: 25, ingredients: ["生菜", "小番茄x2", "玉米粒"] },
        { name: "汉堡", price: 45, ingredients: ["汉堡胚", "生菜x2", "肉饼", "煎蛋", "芝士x2"] },
        { name: "沙拉", price: 25, ingredients: ["生菜", "黄瓜x2", "玉米粒"] },
        { name: "水果茶", price: 20, ingredients: ["西瓜", "百香果", "绿茶"] },
        { name: "水果茶", price: 20, ingredients: ["西瓜", "柠檬", "绿茶"] },
        { name: "汉堡", price: 40, ingredients: ["汉堡胚", "生菜", "肉饼x2", "芝士x2"] },
        { name: "沙拉", price: 30, ingredients: ["生菜", "黄瓜", "小番茄x2", "玉米粒"] },
        { name: "汉堡", price: 35, ingredients: ["汉堡胚", "生菜x2", "番茄", "煎蛋", "芝士"] },
        { name: "水果茶", price: 20, ingredients: ["百香果", "柠檬", "绿茶"] },
        { name: "汉堡", price: 30, ingredients: ["汉堡胚", "生菜", "番茄", "肉饼", "芝士"] },
        { name: "沙拉", price: 25, ingredients: ["生菜", "黄瓜", "小番茄", "玉米粒"] },
        { name: "水果茶", price: 25, ingredients: ["西瓜", "百香果", "柠檬", "绿茶"] },
        { name: "汉堡", price: 45, ingredients: ["汉堡胚", "生菜x2", "番茄", "煎蛋x2", "芝士"] },
        { name: "沙拉", price: 35, ingredients: ["生菜", "黄瓜x2", "小番茄x2", "玉米粒"] },
    ]),
    teamB: addOrderNo([
        { name: "B类沙拉", price: 25, ingredients: ["生菜", "黄瓜", "小番茄", "玉米粒"] },
        { name: "B类水果茶", price: 25, ingredients: ["西瓜", "百香果", "柠檬", "绿茶"] },
        { name: "B类汉堡", price: 40, ingredients: ["汉堡胚", "生菜", "番茄", "肉饼x2", "芝士"] },
        { name: "水果茶", price: 25, ingredients: ["西瓜", "百香果", "柠檬", "绿茶"] },
        { name: "汉堡", price: 50, ingredients: ["汉堡胚", "生菜x2", "番茄", "肉饼", "煎蛋", "芝士x2"] },
        { name: "水果茶", price: 20, ingredients: ["百香果", "柠檬", "绿茶"] },
        { name: "沙拉", price: 25, ingredients: ["生菜", "小番茄x2", "玉米粒"] },
        { name: "沙拉", price: 35, ingredients: ["生菜", "黄瓜x2", "小番茄x2", "玉米粒"] },
        { name: "汉堡", price: 40, ingredients: ["汉堡胚", "生菜", "肉饼", "煎蛋", "芝士x2"] },
        { name: "水果茶", price: 20, ingredients: ["西瓜", "柠檬", "绿茶"] },
        { name: "汉堡", price: 35, ingredients: ["汉堡胚", "生菜x2", "番茄", "煎蛋", "芝士"] },
        { name: "沙拉", price: 25, ingredients: ["生菜", "黄瓜x2", "玉米粒"] },
        { name: "水果茶", price: 20, ingredients: ["西瓜", "百香果", "绿茶"] },
        { name: "汉堡", price: 40, ingredients: ["汉堡胚", "生菜", "肉饼x2", "芝士x2"] },
        { name: "沙拉", price: 25, ingredients: ["生菜", "黄瓜x2", "小番茄"] },
        { name: "汉堡", price: 40, ingredients: ["汉堡胚", "生菜", "番茄", "肉饼", "煎蛋", "芝士"] },
        { name: "水果茶", price: 20, ingredients: ["百香果", "柠檬", "绿茶"] },
        { name: "沙拉", price: 30, ingredients: ["生菜", "黄瓜", "小番茄x2", "玉米粒"] },
        { name: "沙拉", price: 35, ingredients: ["生菜", "黄瓜x2", "小番茄x2", "玉米粒"] },
        { name: "汉堡", price: 40, ingredients: ["汉堡胚", "生菜", "番茄", "肉饼", "煎蛋", "芝士"] },
    ]),
    sharedOrders: addOrderNo([
        { name: "水果茶", price: 25, ingredients: ["西瓜", "百香果", "柠檬", "绿茶"] },
        { name: "汉堡", price: 50, ingredients: ["汉堡胚", "生菜x2", "番茄", "肉饼", "煎蛋", "芝士x2"] },
        { name: "水果茶", price: 25, ingredients: ["西瓜", "百香果", "柠檬", "绿茶"] },
        { name: "水果茶", price: 20, ingredients: ["百香果", "柠檬", "绿茶"] },
        { name: "汉堡", price: 40, ingredients: ["汉堡胚", "生菜", "肉饼x2", "芝士x2"] },
        { name: "沙拉", price: 35, ingredients: ["生菜", "黄瓜x2", "小番茄x2", "玉米粒"] },
        { name: "汉堡", price: 45, ingredients: ["汉堡胚", "生菜x2", "番茄", "煎蛋x2", "芝士"] },
        { name: "水果茶", price: 25, ingredients: ["西瓜", "百香果", "柠檬", "绿茶"] },
        { name: "汉堡", price: 40, ingredients: ["汉堡胚", "生菜", "番茄", "肉饼x2", "芝士"] },
        { name: "水果茶", price: 20, ingredients: ["百香果", "柠檬", "绿茶"] },
        { name: "沙拉", price: 35, ingredients: ["生菜", "黄瓜x2", "小番茄x2", "玉米粒"] },
        { name: "水果茶", price: 25, ingredients: ["西瓜", "百香果", "柠檬", "绿茶"] },
        { name: "汉堡", price: 40, ingredients: ["汉堡胚", "生菜", "肉饼", "煎蛋", "芝士x2"] },
        { name: "沙拉", price: 25, ingredients: ["生菜", "小番茄x2", "玉米粒"] },
        { name: "汉堡", price: 40, ingredients: ["汉堡胚", "生菜", "番茄", "肉饼", "煎蛋", "芝士"] },
        { name: "水果茶", price: 20, ingredients: ["百香果", "柠檬", "绿茶"] },
        { name: "沙拉", price: 30, ingredients: ["生菜", "黄瓜x2", "小番茄x2"] },
        { name: "汉堡", price: 50, ingredients: ["汉堡胚", "生菜x2", "番茄", "肉饼", "煎蛋", "芝士x2"] },
        { name: "沙拉", price: 25, ingredients: ["生菜", "黄瓜x2", "玉米粒"] },
        { name: "沙拉", price: 30, ingredients: ["生菜", "黄瓜", "小番茄x2", "玉米粒"] },
        { name: "水果茶", price: 20, ingredients: ["西瓜", "柠檬", "绿茶"] },
        { name: "汉堡", price: 40, ingredients: ["汉堡胚", "生菜", "番茄", "肉饼x2", "芝士"] },
        { name: "沙拉", price: 30, ingredients: ["生菜", "黄瓜x2", "小番茄x2"] },
        { name: "水果茶", price: 20, ingredients: ["西瓜", "柠檬", "绿茶"] },
        { name: "沙拉", price: 25, ingredients: ["生菜", "小番茄x2", "玉米粒"] },
        { name: "汉堡", price: 40, ingredients: ["汉堡胚", "生菜", "番茄", "肉饼x2", "芝士"] },
        { name: "水果茶", price: 25, ingredients: ["西瓜", "百香果", "柠檬", "绿茶"] },
        { name: "汉堡", price: 40, ingredients: ["汉堡胚", "生菜", "番茄", "肉饼", "煎蛋", "芝士"] },
        { name: "沙拉", price: 25, ingredients: ["生菜", "黄瓜", "小番茄", "玉米粒"] },
        { name: "汉堡", price: 40, ingredients: ["汉堡胚", "生菜", "肉饼", "煎蛋", "芝士x2"] },
        { name: "水果茶", price: 25, ingredients: ["西瓜", "百香果", "柠檬", "绿茶"] },
        { name: "沙拉", price: 25, ingredients: ["生菜", "黄瓜", "小番茄", "玉米粒"] },
        { name: "水果茶", price: 20, ingredients: ["百香果", "柠檬", "绿茶"] },
        { name: "汉堡", price: 35, ingredients: ["汉堡胚", "生菜x2", "番茄", "肉饼", "芝士"] },
        { name: "沙拉", price: 35, ingredients: ["生菜", "黄瓜x2", "小番茄x2", "玉米粒"] },
        { name: "水果茶", price: 20, ingredients: ["西瓜", "柠檬", "绿茶"] },
        { name: "汉堡", price: 40, ingredients: ["汉堡胚", "生菜", "番茄", "肉饼", "煎蛋", "芝士"] },
        { name: "沙拉", price: 30, ingredients: ["生菜", "黄瓜x2", "小番茄x2"] },
        { name: "水果茶", price: 25, ingredients: ["西瓜", "百香果", "柠檬", "绿茶"] },
        { name: "汉堡", price: 40, ingredients: ["汉堡胚", "生菜", "肉饼x2", "芝士x2"] },
    ]),
};